/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookbookRouteImport } from './routes/cookbook'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as PuppyRouteImport } from './routes/puppy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookbookRoute = CookbookRouteImport.update({
  id: '/cookbook',
  path: '/cookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const PuppyRoute = PuppyRouteImport.update({
  id: '/puppy',
  path: '/puppy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/guide': typeof GuideRoute
  '/puppy': typeof PuppyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/guide': typeof GuideRoute
  '/puppy': typeof PuppyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookbook': typeof CookbookRoute
  '/guide': typeof GuideRoute
  '/puppy': typeof PuppyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cookbook' | '/guide' | '/puppy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cookbook' | '/guide' | '/puppy'
  id: '__root__' | '/' | '/cookbook' | '/guide' | '/puppy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookbookRoute: typeof CookbookRoute
  GuideRoute: typeof GuideRoute
  PuppyRoute: typeof PuppyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookbook': {
      id: '/cookbook'
      path: '/cookbook'
      fullPath: '/cookbook'
      preLoaderRoute: typeof CookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puppy': {
      id: '/puppy'
      path: '/puppy'
      fullPath: '/puppy'
      preLoaderRoute: typeof PuppyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookbookRoute: CookbookRoute,
  GuideRoute: GuideRoute,
  PuppyRoute: PuppyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
